modLoader = "kotlinforforge"
loaderVersion = "[${kotlin_for_forge_version},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "Interstellar (ModFest Edition)"
authors = "RedstoneWizard08, Nionics, Bogdanasaurus, LopyLuna, MilkyFur, The_seVen_, CHAZBOMB1, Stardust Modding Contributors"
description = "Explore the universe in style."
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "fzzy_config"
mandatory = true
versionRange = "[${fzzy_config},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "kotlinforforge"
mandatory = true
versionRange = "[${kotlin_for_forge_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "interstellar.mixins.json"

[[mixins]]
config = "interstellar-common.mixins.json"
