modLoader = "kotlinforforge"
loaderVersion = "[5.6,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "Interstellar"
authors = "RedstoneWizard08, Nionics, Bogdanasaurus, Stardust Modding Contributors"
description = "Explore the universe in style."
#logoFile = ""

[[dependencies.${mod_id}]]
modId = "neoforge"
mandatory = true
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "fzzy_config"
mandatory = true
versionRange = "[0.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "interstellar.mixins.json"

[[mixins]]
config = "interstellar-common.mixins.json"
